import { Inter } from "next/font/google";
import "../globals.css";
import { dbConnect } from "@/service/dbConnect";
import Navbar from "../components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stay-Swift",
  description: "Generated by Stay-Swift with next.js",
};

export default async function RootLayout({ children }) {
  // connect database
  await dbConnect();

  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar sideMenu={true}/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
